language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - extra-google-m2repository
  - extra-android-m2repository
script: "./gradlew assembleRelease"
before_install:
- openssl aes-256-cbc -K $encrypted_4ee3680b536c_key -iv $encrypted_4ee3680b536c_iv
  -in hansffu.jks.enc -out hansffu.jks -d
