query StopPlace($id: String!, $lineIds: [ID], $includeLineCatalog: Boolean! = false) {
    stopPlace(id: $id) {
        id
        name
        latitude
        longitude
        estimatedCalls(
            numberOfDepartures: 100,
            numberOfDeparturesPerLineAndDestinationDisplay: 4,
            includeCancelledTrips: false,
            timeRange: 3600,
            whiteListed: { lines: $lineIds },
        ){
            aimedArrivalTime
            expectedArrivalTime
            destinationDisplay{
                frontText
            }
            serviceJourney{
                line{
                    publicCode
                    presentation {
                        colour
                        textColour
                    }
                }
            }
        }
        quays @include(if: $includeLineCatalog) {
            lines {
                id
                publicCode
            }
        }
    }
}
